apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-crm
  labels:
    app: demo-crm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-crm
  template:
    metadata:
      labels:
        app: demo-crm
    spec:
      containers:
      - name: demo-crm
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-crm-service
spec:
  selector:
    app: demo-crm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
