name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and tag image
        run: |
          docker pull pwstaging/demo-crm:latest
          docker tag pwstaging/demo-crm:latest ${{ secrets.DOCKERHUB_USERNAME }}/demo-crm:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-crm:${{ github.sha }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kind
        uses: helm/kind-action@v1.5.0

      - name: Create kind cluster
        run: kind create cluster --name demo-crm

      - name: Load image into kind
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/demo-crm:${{ github.sha }}
          kind load docker-image ${{ secrets.DOCKERHUB_USERNAME }}/demo-crm:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to kind
        run: |
          kubectl apply -f k8s/deployment.yaml
          sleep 20
          kubectl get pods

      - name: Test HTTP connectivity
        run: |
          kubectl port-forward deployment/demo-crm 3000:3000 &
          sleep 10
          curl -f http://localhost:3000 || exit 1
